---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ansible_test-01
    image: solita/ubuntu-systemd:16.04
    privileged: True
    command: /sbin/init
    capabilities:
      - SYS_ADMIN    
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    groups:
      - group1
  # In docker cannot be tested with centos 7 due to https://github.com/ansible/ansible-modules-core/issues/593
  - name: ansible_test-03
    image: centos/systemd
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    privileged: True
    groups:
      - group1
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
    role-file: tests/requirements.yml
